CREATE DATABASE BMS_DB1;

USE BMS_DB1;

-- CUSTOMER PERSONAL INFO
CREATE TABLE CUSTOMER_PERSONAL_INFO
(
	CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(30),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(20),
    CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);

SHOW TABLES;

-- CUSTOMER REFERENCE INFO
CREATE TABLE CUSTOMER_REFERENCE_INFO
(
	CUSTOMER_ID VARCHAR(5),
    REFERENCE_ACC_NAME VARCHAR(20),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
    CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

SHOW TABLES;

-- BANK INFO
CREATE TABLE BANK_INFO
(
	IFSC_CODE VARCHAR(15),
    BANK_NAME VARCHAR(25),
    BRANCH_NAME VARCHAR(25),
    CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

SHOW TABLES;

-- ACCOUNT INFO
CREATE TABLE ACOUNT_INFO
(
	ACCOUNT_NO BIGINT(16),
    CUSTOMER_ID VARCHAR(5),
    ACCOUNT_TYPE VARCHAR(10),
    REGISTRATION_DATE DATE,
    ACTIVATION_DATE DATE,
    IFSC_CODE VARCHAR(10),
    INTEREST DECIMAL(7,2),
    INITIAL_DEPOSIT BIGINT(10),
    CONSTRAINT ACC_INFO_PK PRIMARY KEY (ACCOUNT_NO)
);

SHOW TABLES;

INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HCG1002','SBI','BLS');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBN5648','AXIS','BBSR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('JDM7598','PNB','BDK');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('AVD1212','ICICI','CTC');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('AKL4164','FBI','SORO');

SELECT * FROM BANK_INFO;

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES('64844','SP Das','2000-09-02','RK Das','Bangalore','8634851158','xyz@gmail.com','M','Married','aadhar','41934138','Indian');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES('64846','LP Das','2000-09-03','RS Das','Delhi','8634864858','pqr@gmail.com','F','Bachelor','PAN','419684638','Arabian');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES('46846','MP Das','2000-09-04','RT Das','Punjab','86345841158','abc@gmail.com','F','Married','VOTER','41635338','Sri Lankan');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP) VALUES('12984','RP Das','2000-09-05','RV Das','Hyderabad','86344369158','mnno@gmail.com','M','Bachelor','DL','414643338','American');

SELECT * FROM CUSTOMER_PERSONAL_INFO;

INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS) VALUES('18946','SP Das','46452563','Bangalore');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS) VALUES('17851','LP Das','19813126','Delhi');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS) VALUES('16401','MP Das','17861616','Punjab');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS) VALUES('18946','RP Das','17869562','Hyerabad');

SELECT * FROM CUSTOMER_REFERENCE_INFO;

INSERT INTO ACOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES('41684521688','18946','Savings','2019-04-06','2019-12-03','HCG1002','4.3','10000'); 
INSERT INTO ACOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES('71631681313','17851','Children','2019-06-26','2019-11-03','SBN5648','2.3','20000');
INSERT INTO ACOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES('19835468468','16401','Insurance','2019-11-16','2019-10-13','JDM7598','4.7','30000'); 
INSERT INTO ACOUNT_INFO(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,IFSC_CODE,INTEREST,INITIAL_DEPOSIT) VALUES('12983512684','18946','Savings','2019-04-15','2019-02-01','AVD1212','5.3','40000');

SELECT * FROM ACOUNT_INFO  